import type { UserOption } from './common';

export type CompanyRelationshipListItem = {
    id: number;
    related_company_id: number;
    related_company_name: string | null;
    kind: string;
    status: string;
    classification: string;
    brand_name: string | null;
    owner_reference: string | null;
    created_at: string | null;
};

export type CompanyRelationshipFormData = {
    id: number;
    owner_company_id: number;
    related_company_id: number;
    related_company_name: string | null;
    priority_ids: number[];
    collaborator_ids: number[];
    service_type_ids: number[];
    global_service_type_ids: number[];
    alternative_delegation_ids: number[];
    kind: string;
    status: string;
    classification: string;
    owner_reference: string | null;
    related_reference: string | null;
    brand_id: number | null;
    external_code: string | null;
    notes: string | null;
    starts_at: string | null;
    ends_at: string | null;
    delegation_id: number | null;
    billing_language_id: number | null;
    series_id: number | null;
    integration_id: number | null;
    integration_external_id: string | null;
    corrective_work_order_owner_id: number | null;
    preventive_work_order_owner_id: number | null;
    quality_owner_id: number | null;
    account_owner_id: number | null;
    commercial_owner_id: number | null;
    sourced_by_user_id: number | null;
    internal_notes: string | null;
    notes_alert: boolean | null;
    internal_notes_alert: boolean | null;
    onboarding_notes: string | null;
    billing_comments: string | null;
    rates_notes: string | null;
    archetype: string | null;
    tax_rate: number | string | null;
    is_reviewed: boolean | null;
    is_email_reviewed: boolean | null;
    is_invoicing_reviewed: boolean | null;
    invoicing_reviewed_at: string | null;
    quote_close_days: number | null;
    recurring_meeting_frequency: number | null;
    sales_feedback_meeting_frequency: number | null;
    group_zero_cost_work_orders: boolean | null;
    load_materials_on_corrective: boolean | null;
    group_preventive_and_corrective: boolean | null;
    group_preventives_by: string | null;
    group_correctives_by: string | null;
    invoice_at_month_end: boolean | null;
    requires_purchase_order: boolean | null;
    requires_requester: boolean | null;
    is_franchise: boolean | null;
    requires_justification: boolean | null;
    auto_send_invoices: boolean | null;
    send_invoices_individually: boolean | null;
    send_debt_reminders: boolean | null;
    is_quality_control_contactable: boolean | null;
    requires_client_informed_check: boolean | null;
    requires_intervention_scheduled_check: boolean | null;
    requires_budget_approval_limit: boolean | null;
    is_intercompany: boolean | null;
    optima_score: number | string | null;
    customer_score: number | string | null;
    average_score: number | string | null;
    optima_score_count: number | null;
    customer_score_count: number | null;
    has_health_and_safety: boolean | null;
    is_field_technician: boolean | null;
    is_creditor: boolean | null;
    is_vip: boolean | null;
    is_available_24h: boolean | null;
    day_start_at: string | null;
    day_end_at: string | null;
    has_garnishment: boolean | null;
    whatsapp_messaging_authorized: boolean | null;
    registered_at: string | null;
    legacy_status_id: number | null;
};

export type RelationshipFormOptions = {
    brandOptions: UserOption[];
    delegationOptions: UserOption[];
    languageOptions: UserOption[];
    seriesOptions: UserOption[];
    integrationOptions: UserOption[];
    userOptions: UserOption[];
    priorityOptions: UserOption[];
    serviceTypeOptions: UserOption[];
    globalServiceTypeOptions: UserOption[];
};
