/**
 * Semantic field-help keys. Optional DX helper — backend `key` remains source of truth.
 * Only list keys that are expected to need curated help (not obvious labels).
 */
export const fieldHelpKeys = {
    companies: {
        taxId: 'companies.tax_id',
        kind: 'companies.kind',
        personType: 'companies.person_type',
        residenceCountry: 'companies.residence_country_id',
        legacyErpId: 'companies.legacy_erp_id',
    },
    companyRelationships: {
        ownerReference: 'company_relationships.owner_reference',
        relatedReference: 'company_relationships.related_reference',
        classification: 'company_relationships.classification',
        integrationExternalId: 'company_relationships.integration_external_id',
        reportedCustomerRelationship: 'company_relationships.reported_customer_relationship_id',
        archetype: 'company_relationships.archetype',
        quoteCloseDays: 'company_relationships.quote_close_days',
        recurringMeetingFrequency: 'company_relationships.recurring_meeting_frequency',
        salesFeedbackMeetingFrequency: 'company_relationships.sales_feedback_meeting_frequency',
        groupPreventivesBy: 'company_relationships.group_preventives_by',
        groupCorrectivesBy: 'company_relationships.group_correctives_by',
        groupZeroCostWorkOrders: 'company_relationships.group_zero_cost_work_orders',
        loadMaterialsOnCorrective: 'company_relationships.load_materials_on_corrective',
        groupPreventiveAndCorrective: 'company_relationships.group_preventive_and_corrective',
        requiresPurchaseOrder: 'company_relationships.requires_purchase_order',
        requiresRequester: 'company_relationships.requires_requester',
        requiresJustification: 'company_relationships.requires_justification',
        sendInvoicesIndividually: 'company_relationships.send_invoices_individually',
        isQualityControlContactable: 'company_relationships.is_quality_control_contactable',
        requiresClientInformedCheck: 'company_relationships.requires_client_informed_check',
        requiresInterventionScheduledCheck: 'company_relationships.requires_intervention_scheduled_check',
        requiresBudgetApprovalLimit: 'company_relationships.requires_budget_approval_limit',
        isIntercompany: 'company_relationships.is_intercompany',
        optimaScore: 'company_relationships.optima_score',
        customerScore: 'company_relationships.customer_score',
        averageScore: 'company_relationships.average_score',
        isFieldTechnician: 'company_relationships.is_field_technician',
        isCreditor: 'company_relationships.is_creditor',
        hasGarnishment: 'company_relationships.has_garnishment',
        whatsappMessagingAuthorized: 'company_relationships.whatsapp_messaging_authorized',
        legacyStatusId: 'company_relationships.legacy_status_id',
        invoiceAtMonthEnd: 'company_relationships.invoice_at_month_end',
        autoSendInvoices: 'company_relationships.auto_send_invoices',
        sendDebtReminders: 'company_relationships.send_debt_reminders',
        isFranchise: 'company_relationships.is_franchise',
        isAvailable24h: 'company_relationships.is_available_24h',
        hasHealthAndSafety: 'company_relationships.has_health_and_safety',
    },
    establishments: {
        storeCode: 'establishments.store_code',
        alternateStoreCode: 'establishments.alternate_store_code',
        emails: 'establishments.emails',
        recipientEmails: 'establishments.recipient_emails',
        billingCompany: 'establishments.billing_company_id',
        taxIncluded: 'establishments.tax_included',
        legacyErpId: 'establishments.legacy_erp_id',
        integrationExternalId: 'establishments.integration_external_id',
        hasSiteHealthAndSafety: 'establishments.has_site_health_and_safety',
        hasCustomerHealthAndSafety: 'establishments.has_customer_health_and_safety',
        isClientPriority: 'establishments.is_client_priority',
        isUlezZone: 'establishments.is_ulez_zone',
        notesAlert: 'establishments.notes_alert',
        internalNotesAlert: 'establishments.internal_notes_alert',
    },
    brands: {
        loyaltyMeetingFrequency: 'brands.loyalty_meeting_frequency',
        isQualityControlContactable: 'brands.is_quality_control_contactable',
        sendDebtReminders: 'brands.send_debt_reminders',
        corporationCompany: 'brands.corporation_company_id',
    },
} as const;
