<?php

declare(strict_types=1);

namespace Tests\Unit\Domain\Auth;

use App\Domain\Auth\Permissions\PolicyPermissionDiscoverer;
use App\Policies\RolePolicy;
use App\Policies\UserPolicy;
use Tests\TestCase;

final class PolicyPermissionDiscovererTest extends TestCase
{
    public function test_it_discovers_permissions_from_policy_methods(): void
    {
        $discoverer = new PolicyPermissionDiscoverer;
        $permissions = $discoverer->discover();

        $this->assertContains(UserPolicy::class, $discoverer->policyClasses());
        $this->assertContains(RolePolicy::class, $discoverer->policyClasses());

        $this->assertSame([
            'banks.create',
            'banks.delete',
            'banks.update',
            'banks.view',
            'brands.create',
            'brands.delete',
            'brands.download-message-files',
            'brands.send-message-files',
            'brands.send-messages',
            'brands.update',
            'brands.view',
            'brands.view-message-files',
            'brands.view-messages',
            'client_priorities.create',
            'client_priorities.delete',
            'client_priorities.update',
            'client_priorities.view',
            'companies.create',
            'companies.delete',
            'companies.update',
            'companies.view',
            'company_relationships.create',
            'company_relationships.delete',
            'company_relationships.update',
            'company_relationships.view',
            'contract_statuses.create',
            'contract_statuses.delete',
            'contract_statuses.update',
            'contract_statuses.view',
            'contracts.create',
            'contracts.delete',
            'contracts.delete-attachments',
            'contracts.download-attachments',
            'contracts.update',
            'contracts.upload-attachments',
            'contracts.view',
            'contracts.view-attachments',
            'countries.create',
            'countries.delete',
            'countries.update',
            'countries.view',
            'currencies.create',
            'currencies.delete',
            'currencies.update',
            'currencies.view',
            'delegations.create',
            'delegations.delete',
            'delegations.update',
            'delegations.view',
            'establishment_types.create',
            'establishment_types.delete',
            'establishment_types.update',
            'establishment_types.view',
            'establishments.create',
            'establishments.delete',
            'establishments.update',
            'establishments.view',
            'evaluation_statuses.create',
            'evaluation_statuses.delete',
            'evaluation_statuses.update',
            'evaluation_statuses.view',
            'evaluations.create',
            'evaluations.delete',
            'evaluations.update',
            'evaluations.view',
            'field_helps.create',
            'field_helps.delete',
            'field_helps.update',
            'field_helps.view',
            'incident_priorities.create',
            'incident_priorities.delete',
            'incident_priorities.update',
            'incident_priorities.view',
            'incident_statuses.create',
            'incident_statuses.delete',
            'incident_statuses.update',
            'incident_statuses.view',
            'incident_subtypes.create',
            'incident_subtypes.delete',
            'incident_subtypes.update',
            'incident_subtypes.view',
            'incident_types.create',
            'incident_types.delete',
            'incident_types.update',
            'incident_types.view',
            'incidents.create',
            'incidents.delete',
            'incidents.update',
            'incidents.view',
            'integrations.create',
            'integrations.delete',
            'integrations.update',
            'integrations.view',
            'languages.create',
            'languages.delete',
            'languages.update',
            'languages.view',
            'numbering_patterns.create',
            'numbering_patterns.delete',
            'numbering_patterns.update',
            'numbering_patterns.view',
            'provinces.create',
            'provinces.delete',
            'provinces.update',
            'provinces.view',
            'rating_types.create',
            'rating_types.delete',
            'rating_types.update',
            'rating_types.view',
            'roles.create',
            'roles.delete',
            'roles.update',
            'roles.view',
            'series.create',
            'series.delete',
            'series.update',
            'series.view',
            'teams.create',
            'teams.delete',
            'teams.update',
            'teams.view',
            'timezones.create',
            'timezones.delete',
            'timezones.update',
            'timezones.view',
            'users.create',
            'users.delete',
            'users.update',
            'users.view',
            'work_order_statuses.create',
            'work_order_statuses.delete',
            'work_order_statuses.update',
            'work_order_statuses.view',
            'work_order_types.create',
            'work_order_types.delete',
            'work_order_types.update',
            'work_order_types.view',
        ], $permissions);
    }
}
